/*  paises: 
    Array de objetos con la información de cada país (201) y si requiere o no 
    permiso para ingresar a Chile
*/

const paises = [
    {
        id: 1,
        pais: "Afganistán",
        bandera: "afganistan.svg",
        emoji: "🇦🇫",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 30,
        estadiaMultiple: 60,
        costoMultiple: 68,
        costoResidencia: 100
    },
    {
        id: 2,
        pais: "Albania",
        bandera: "albania.svg",
        emoji: "🇦🇱",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 140
    },
    {
        id: 3,
        pais: "Alemania",
        bandera: "alemania.svg",
        emoji: "🇩🇪",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 85
    },
    {
        id: 4,
        pais: "Andorra",
        bandera: "andorra.svg",
        emoji: "🇦🇩",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 100
    },
    {
        id: 5,
        pais: "Angola",
        bandera: "angola.svg",
        emoji: "🇦🇴",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 80,
        estadiaMultiple: 90,
        costoMultiple: 108,
        costoResidencia: 150
    },
    {
        id: 6,
        pais: "Antigua y Barbuda",
        bandera: "antigua-y-barbuda.svg",
        emoji: "🇦🇬",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 120
    },
    {
        id: 7,
        pais: "Antillas Holandesas",
        bandera: "antillas-holandesas.svg",
        emoji: "🇦🇼 🇧🇶 🇨🇼",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 192
    },
    {
        id: 8,
        pais: "Arabia Saudita",
        bandera: "arabia-saudita.svg",
        emoji: "🇸🇦",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 28,
        estadiaMultiple: 90,
        costoMultiple: 93,
        costoResidencia: 43
    },
    {
        id: 9,
        pais: "Argelia",
        bandera: "argelia.svg",
        emoji: "🇩🇿",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 40,
        estadiaMultiple: 90,
        costoMultiple: 48,
        costoResidencia: 40
    },
    {
        id: 10,
        pais: "Argentina",
        bandera: "argentina.svg",
        emoji: "🇦🇷",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 250
    },
    {
        id: 11,
        pais: "Armenia",
        bandera: "armenia.svg",
        emoji: "🇦🇲",
        permiso: "si",
        estadiaSimple: 21,
        costoSimple: 37,
        estadiaMultiple: 90,
        costoMultiple: 58,
        costoResidencia: 200
    },
    {
        // Australia requiere además de permiso de ingreso previo para personas en tránsito
        id: 12,
        pais: "Australia",
        bandera: "australia.svg",
        emoji: "🇦🇺",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 105,
        estadiaMultiple: 90,
        costoMultiple: 105,
        costoResidencia: 225
    },
    {
        id: 13,
        pais: "Austria",
        bandera: "austria.svg",
        emoji: "🇦🇹",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 100
    },
    {
        id: 14,
        pais: "Azerbaiyán",
        bandera: "azerbaiyan.svg",
        emoji: "🇦🇿",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 40,
        estadiaMultiple: 90,
        costoMultiple: 88,
        costoResidencia: 25
    },
    {
        id: 15,
        pais: "Bahamas",
        bandera: "bahamas.svg",
        emoji: "🇧🇸",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 25
    },
    {
        id: 16,
        pais: "Barein",
        bandera: "barein.svg",
        emoji: "🇧🇭",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 15,
        estadiaMultiple: 30,
        costoMultiple: 75,
        costoResidencia: 119
    },
    {
        id: 17,
        pais: "Bangladesh",
        bandera: "bangladesh.svg",
        emoji: "🇧🇩",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 10,
        estadiaMultiple: 90,
        costoMultiple: 18,
        costoResidencia: 12
    },
    {
        id: 18,
        pais: "Barbados",
        bandera: "barbados.svg",
        emoji: "🇧🇧",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 300
    },
    {
        // Exento VISTUR para nacionales de Belarús con REDE en países de la Alianza del Pacífico (Colombia-Mexico-Perú) a contar del 16 de junio de 2017
        id: 19,
        pais: "Bielorrusia",
        bandera: "bielorrusia.svg",
        emoji: "🇧🇾",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 60,
        estadiaMultiple: 90,
        costoMultiple: 128,
        costoResidencia: 270
    },
    {
        id: 20,
        pais: "Bélgica",
        bandera: "belgica.svg",
        emoji: "🇧🇪",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 202
    },
    {
        id: 21,
        pais: "Belice",
        bandera: "belice.svg",
        emoji: "🇧🇿",
        permiso: "no",
        estadiaSimple: 30,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 625
    },
    {
        id: 22,
        pais: "Benin",
        bandera: "benin.svg",
        emoji: "🇧🇯",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 54,
        estadiaMultiple: 60,
        costoMultiple: 68,
        costoResidencia: 60
    },
    {
        id: 23,
        pais: "Bolivia",
        bandera: "bolivia.svg",
        emoji: "🇧🇴",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 149
    },
    {
        id: 24,
        pais: "Bosnia y Herzegovina",
        bandera: "bosnia.svg",
        emoji: "🇧🇦",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 122
    },
    {
        // Exento de VISTUR para nacionales de Botswana con REDE en países de la Alianza del Pacífico (Colombia-Mexico-Peru) a contar del 30 de junio de 2016
        id: 25,
        pais: "Botsuana",
        bandera: "botsuana.svg",
        emoji: "🇧🇼",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 92,
        estadiaMultiple: 90,
        costoMultiple: 146,
        costoResidencia: 138
    },
    {
        id: 26,
        pais: "Brasil",
        bandera: "brasil.svg",
        emoji: "🇧🇷",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 100
    },
    {
        // Exento de VISTUR para nacionales de Brunéi con REDE en países de la Alianza del Pacífico (Colombia-Mexico-Peru) a contar del 30 de junio de 2016
        id: 27,
        pais: "Brunéi",
        bandera: "brunei.svg",
        emoji: "🇧🇳",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 16,
        estadiaMultiple: 90,
        costoMultiple: 33,
        costoResidencia: 16
    },
    {
        id: 28,
        pais: "Bulgaria",
        bandera: "bulgaria.svg",
        emoji: "🇧🇬",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 136
    },
    {
        // Exento de VISTUR para nacionales de Burkina Faso con REDE en países de la Alianza del Pacífico (Colombia-Mexico-Peru) a contar del 16 de junio 2017
        id: 29,
        pais: "Burkina Faso",
        bandera: "burkina-faso.svg",
        emoji: "🇧🇫",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: 90,
        costoMultiple: 108,
        costoResidencia: 60
    },
    {
        id: 30,
        pais: "Burundi",
        bandera: "burundi.svg",
        emoji: "🇧🇮",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 90,
        estadiaMultiple: 90,
        costoMultiple: 128,
        costoResidencia: 60
    },
    {
        id: 31,
        pais: "Bután",
        bandera: "butan.svg",
        emoji: "🇧🇹",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: 90,
        costoMultiple: 108,
        costoResidencia: 60
    },
    {
        id: 32,
        pais: "Cabo Verde",
        bandera: "cabo-verde.svg",
        emoji: "🇨🇻",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: 90,
        costoMultiple: 108,
        costoResidencia: 60
    },
    {
        // Exento VISTUR nacionales de Camboya con REDE en países de la Alianza del Pacífico (Colombia-Mexico-Peru) a contar del 30 de junio de 2016
        id: 33,
        pais: "Camboya",
        bandera: "camboya.svg",
        emoji: "🇰🇭",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 30,
        estadiaMultiple: 30,
        costoMultiple: 44,
        costoResidencia: 100
    },
    {
        id: 34,
        pais: "Camerún",
        bandera: "camerun.svg",
        emoji: "🇨🇲",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 25,
        estadiaMultiple: 60,
        costoMultiple: 58,
        costoResidencia: 40
    },
    {
        id: 35,
        pais: "Canadá",
        bandera: "canada.svg",
        emoji: "🇨🇦",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 265
    },
    {
        id: 36,
        pais: "Chad",
        bandera: "chad.svg",
        emoji: "🇹🇩",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: 90,
        costoMultiple: 108,
        costoResidencia: 60
    },
    {
        id: 37,
        pais: "China",
        bandera: "china.svg",
        emoji: "🇨🇳",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 42
    },
    {
        id: 38,
        pais: "Chipre",
        bandera: "chipre.svg",
        emoji: "🇨🇾",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 122
    },
    {
        id: 39,
        pais: "Colombia",
        bandera: "colombia.svg",
        emoji: "🇨🇴",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 282
    },
    {
        id: 40,
        pais: "Comoras",
        bandera: "comoras.svg",
        emoji: "🇰🇲",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 60
    },
    {
        id: 41,
        pais: "Corea del Norte",
        bandera: "corea-del-norte.svg",
        emoji: "🇰🇵",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 40,
        estadiaMultiple: 90,
        costoMultiple: 48,
        costoResidencia: 40
    },
    {
        id: 42,
        pais: "Corea del Sur",
        bandera: "corea-del-sur.svg",
        emoji: "🇰🇷",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 90
    },
    {
        id: 43,
        pais: "Costa de Marfil",
        bandera: "costa-de-marfil.svg",
        emoji: "🇨🇮",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 66,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 66
    },
    {
        id: 44,
        pais: "Costa Rica",
        bandera: "costa-rica.svg",
        emoji: "🇨🇷",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 650
    },
    {
        id: 45,
        pais: "Croacia",
        bandera: "croacia.svg",
        emoji: "🇭🇷",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 91
    },
    {
        // Exento VISTUR para nacionales de Cuba con REDE en países de la Alianza del Pacífico (Colombia-Mexico-Peru) a contar del 16 de junio de 2017
        id: 46,
        pais: "Cuba",
        bandera: "cuba.svg",
        emoji: "🇨🇺",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 15,
        estadiaMultiple: 30,
        costoMultiple: 108,
        costoResidencia: 88
    },
    {
        id: 47,
        pais: "Dinamarca",
        bandera: "dinamarca.svg",
        emoji: "🇩🇰",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 455
    },
    {
        // Exento del requisito VISTUR de ingreso a Chile para nacionales de Dominica con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 48,
        pais: "Dominica",
        bandera: "dominica.svg",
        emoji: "🇩🇲",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 74,
        estadiaMultiple: 90,
        costoMultiple: 82,
        costoResidencia: 296
    },
    {
        id: 49,
        pais: "Ecuador",
        bandera: "ecuador.svg",
        emoji: "🇪🇨",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 450
    },
    {
        id: 50,
        pais: "Egipto",
        bandera: "egipto.svg",
        emoji: "🇪🇬",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 30,
        estadiaMultiple: 90,
        costoMultiple: 58,
        costoResidencia: 15
    },
    {
        id: 51,
        pais: "El Salvador",
        bandera: "el-salvador.svg",
        emoji: "🇸🇻",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 140
    },
    {
        id: 52,
        pais: "Emiratos Árabes Unidos",
        bandera: "eau.svg",
        emoji: "🇦🇪",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 105
    },
    {
        id: 53,
        pais: "Eritrea",
        bandera: "eritrea.svg",
        emoji: "🇪🇷",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 30,
        estadiaMultiple: 90,
        costoMultiple: 68,
        costoResidencia: 160
    },
    {
        id: 54,
        pais: "Eslovaquia",
        bandera: "eslovaquia.svg",
        emoji: "🇸🇰",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 137
    },
    {
        id: 55,
        pais: "Eslovenia",
        bandera: "eslovenia.svg",
        emoji: "🇸🇮",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 82
    },
    {
        id: 56,
        pais: "España",
        bandera: "espana.svg",
        emoji: "🇪🇸",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 0
    },
    {
        id: 57,
        pais: "Estados Unidos",
        bandera: "eeuu.svg",
        emoji: "🇺🇸",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 205
    },
    {
        id: 58,
        pais: "Estonia",
        bandera: "estonia.svg",
        emoji: "🇪🇪",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 72
    },
    {
        id: 59,
        pais: "Etiopía",
        bandera: "etiopia.svg",
        emoji: "🇪🇹",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 20,
        estadiaMultiple: 60,
        costoMultiple: 58,
        costoResidencia: 30
    },
    {
        id: 60,
        pais: "Fiji",
        bandera: "fiji.svg",
        emoji: "🇫🇯",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 160
    },
    {
        id: 61,
        pais: "Filipinas",
        bandera: "filipinas.svg",
        emoji: "🇵🇭",
        permiso: "si",
        estadiaSimple: 60,
        costoSimple: 40,
        estadiaMultiple: 90,
        costoMultiple: 88,
        costoResidencia: 220
    },
    {
        id: 62,
        pais: "Finlandia",
        bandera: "finlandia.svg",
        emoji: "🇫🇮",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 675
    },
    {
        id: 63,
        pais: "Francia",
        bandera: "francia.svg",
        emoji: "🇫🇷",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 60
    },
    {
        // Exento del requisito VISTUR de ingreso a Chile para nacionales de Gabón con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 64,
        pais: "Gabón",
        bandera: "gabon.svg",
        emoji: "🇬🇦",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 60,
        estadiaMultiple: 90,
        costoMultiple: 68,
        costoResidencia: 60
    },
    {
        id: 65,
        pais: "Gambia",
        bandera: "gambia.svg",
        emoji: "🇬🇲",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 60
    },
    {
        id: 66,
        pais: "Georgia",
        bandera: "georgia.svg",
        emoji: "🇬🇪",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 20
    },
    {
        // Exento del requisito VISTUR de ingreso a Chile para nacionales de Ghana con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 67,
        pais: "Ghana",
        bandera: "ghana.svg",
        emoji: "🇬🇭",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 22,
        estadiaMultiple: 90,
        costoMultiple: 51,
        costoResidencia: 40
    },
    {
        id: 68,
        pais: "Granada",
        bandera: "granada.svg",
        emoji: "🇬🇩",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        id: 69,
        pais: "Grecia",
        bandera: "grecia.svg",
        emoji: "🇬🇷",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 101
    },
    {
        id: 70,
        pais: "Guatemala",
        bandera: "guatemala.svg",
        emoji: "🇬🇹",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 200
    },
    {
        id: 71,
        pais: "Guinea",
        bandera: "guinea.svg",
        emoji: "🇬🇳",
        permiso: "si",
        estadiaSimple: 60,
        costoSimple: 4,
        estadiaMultiple: 60,
        costoMultiple: 12,
        costoResidencia: 95
    },
    {
        id: 72,
        pais: "Guinea-Bisáu",
        bandera: "guinea-bisau.svg",
        emoji: "🇬🇼",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 60
    },
    {
        id: 73,
        pais: "Guinea Ecuatorial",
        bandera: "guinea-ecuatorial.svg",
        emoji: "🇬🇶",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 25,
        estadiaMultiple: 60,
        costoMultiple: 58,
        costoResidencia: 40
    },
    {
        id: 74,
        pais: "Guyana",
        bandera: "guyana.svg",
        emoji: "🇬🇾",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 140
    },
    {
        id: 75,
        pais: "Haití",
        bandera: "haiti.svg",
        emoji: "🇭🇹",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 0,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 25
    },
    {
        id: 76,
        pais: "Honduras",
        bandera: "honduras.svg",
        emoji: "🇭🇳",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 107
    },
    {
        id: 77,
        pais: "Hong Kong",
        bandera: "hong-kong.svg",
        emoji: "🇭🇰",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 30
    },
    {
        id: 78,
        pais: "Hungría",
        bandera: "hungria.svg",
        emoji: "🇭🇺",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 42,
        estadiaMultiple: 90,
        costoMultiple: 76,
        costoResidencia: 123
    },
    {
        // Nacionales de India portadores de una Visa otorgada por EE.UU. (Todos los tipos excepto la Visa C) con a lo menos 6 meses de vigencia, o Green Card, No requieren VISTUR para ingresar a Chile a contar del 1 de abril de 2019
        id: 79,
        pais: "India",
        bandera: "india.svg",
        emoji: "🇮🇳",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 42,
        estadiaMultiple: 90,
        costoMultiple: 76,
        costoResidencia: 123
    },
    {
        // Exención sólo se aplica a VISTUR simple, una entrada, por 60 días plazo máximo
        id: 80,
        pais: "Indonesia",
        bandera: "indonesia.svg",
        emoji: "🇮🇩",
        permiso: "no",
        estadiaSimple: 60,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 123,
        costoResidencia: 110
    },
    {
        id: 81,
        pais: "Irak",
        bandera: "irak.svg",
        emoji: "🇮🇶",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 40,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 73
    },
    {
        id: 82,
        pais: "Irán",
        bandera: "iran.svg",
        emoji: "🇮🇷",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 100,
        estadiaMultiple: 90,
        costoMultiple: 154,
        costoResidencia: 125
    },
    {
        id: 83,
        pais: "Irlanda",
        bandera: "irlanda.svg",
        emoji: "🇮🇪",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 341
    },
    {
        id: 84,
        pais: "Islandia",
        bandera: "islandia.svg",
        emoji: "🇮🇸",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 125
    },
    {
        id: 85,
        pais: "Islas Cook",
        bandera: "islas-cook.svg",
        emoji: "🇨🇰",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        // Exento del requisito VISTUR de ingreso a Chile para nacionales de las Islas Marshall con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 86,
        pais: "Islas Marshall",
        bandera: "islas-marshall.svg",
        emoji: "🇲🇭",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 35,
        estadiaMultiple: 90,
        costoMultiple: 43,
        costoResidencia: 35
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile a nacionales de Islas Salomón con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 16 junio 2017
        id: 87,
        pais: "Islas Salomón",
        bandera: "islas-salomon.svg",
        emoji: "🇸🇧",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 40,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 60
    },
    {
        id: 88,
        pais: "Israel",
        bandera: "israel.svg",
        emoji: "🇮🇱",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        id: 89,
        pais: "Italia",
        bandera: "italia.svg",
        emoji: "🇮🇹",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 261
    },
    {
        id: 90,
        pais: "Jamaica",
        bandera: "jamaica.svg",
        emoji: "🇯🇲",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 150
    },
    {
        id: 91,
        pais: "Japón",
        bandera: "japon.svg",
        emoji: "🇯🇵",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 55
    },
    {
        id: 92,
        pais: "Jordania",
        bandera: "jordania.svg",
        emoji: "🇯🇴",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 56,
        estadiaMultiple: 90,
        costoMultiple: 178,
        costoResidencia: 43
    },
    {
        id: 93,
        pais: "Kazajistán",
        bandera: "kazajistan.svg",
        emoji: "🇰🇿",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 60
    },
    {
        id: 94,
        pais: "Kenia",
        bandera: "kenia.svg",
        emoji: "🇰🇪",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 51,
        estadiaMultiple: 90,
        costoMultiple: 108,
        costoResidencia: 385
    },
    {
        id: 95,
        pais: "Kirguistán",
        bandera: "kirguistan.svg",
        emoji: "🇰🇬",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 36,
        estadiaMultiple: 90,
        costoMultiple: 68,
        costoResidencia: 125
    },
    {
        // Exento del requisito VISTUR de ingreso a Chile para nacionales de Kiribati con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 96,
        pais: "Kiribati",
        bandera: "kiribati.svg",
        emoji: "🇰🇮",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 23,
        estadiaMultiple: 90,
        costoMultiple: 48,
        costoResidencia: 23
    },
    {
        id: 97,
        pais: "Kosovo",
        bandera: "kosovo.svg",
        emoji: "🇽🇰",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 153
    },
    {
        id: 98,
        pais: "Kuwait",
        bandera: "kuwait.svg",
        emoji: "🇰🇼",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 55,
        estadiaMultiple: 30,
        costoMultiple: 63,
        costoResidencia: 40
    },
    {
        // Exento del requisito VISTUR de ingreso a Chile para nacionales de la República Democrática Popular de Laos con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 99,
        pais: "Laos",
        bandera: "laos.svg",
        emoji: "🇱🇦",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 30,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 35
    },
    {
        id: 100,
        pais: "Lesoto",
        bandera: "lesoto.svg",
        emoji: "🇱🇸",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 150,
        estadiaMultiple: 90,
        costoMultiple: 258,
        costoResidencia: 107
    },
    {
        id: 101,
        pais: "Letonia",
        bandera: "letonia.svg",
        emoji: "🇱🇻",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 154
    },
    {
        id: 102,
        pais: "Líbano",
        bandera: "libano.svg",
        emoji: "🇱🇧",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 84,
        estadiaMultiple: 90,
        costoMultiple: 125,
        costoResidencia: 186
    },
    {
        id: 103,
        pais: "Liberia",
        bandera: "liberia.svg",
        emoji: "🇱🇷",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 25,
        estadiaMultiple: 60,
        costoMultiple: 58,
        costoResidencia: 40
    },
    {
        id: 104,
        pais: "Libia",
        bandera: "libia.svg",
        emoji: "🇱🇾",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 63,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 63
    },
    {
        id: 105,
        pais: "Liechtenstein",
        bandera: "liechtenstein.svg",
        emoji: "🇱🇮",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 150
    },
    {
        id: 106,
        pais: "Lituania",
        bandera: "lituania.svg",
        emoji: "🇱🇹",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 65
    },
    {
        id: 107,
        pais: "Luxemburgo",
        bandera: "luxemburgo.svg",
        emoji: "🇱🇺",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 90
    },
    {
        id: 108,
        pais: "Macao",
        bandera: "macao.svg",
        emoji: "🇲🇴",
        permiso: "no",
        estadiaSimple: 30,
        costoSimple: 0,
        estadiaMultiple: 30,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        id: 109,
        pais: "Macedonia del Norte",
        bandera: "macedonia.svg",
        emoji: "🇲🇰",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 51
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile a nacionales de Madagascar con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 110,
        pais: "Madagascar",
        bandera: "madagascar.svg",
        emoji: "🇲🇬",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 25,
        estadiaMultiple: 60,
        costoMultiple: 58,
        costoResidencia: 40
    },
    {
        id: 111,
        pais: "Malasia",
        bandera: "malasia.svg",
        emoji: "🇲🇾",
        permiso: "no",
        estadiaSimple: 30,
        costoSimple: 0,
        estadiaMultiple: 30,
        costoMultiple: 0,
        costoResidencia: 35
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile a nacionales de Malawi con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 112,
        pais: "Malawi",
        bandera: "malawi.svg",
        emoji: "🇲🇼",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 75,
        estadiaMultiple: 90,
        costoMultiple: 83,
        costoResidencia: 40
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile a nacionales de Maldivas con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 16 junio 2017
        id: 113, 
        pais: "Maldivas",
        bandera: "maldivas.svg",
        emoji: "🇲🇻",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 15,
        estadiaMultiple: 90,
        costoMultiple: 38,
        costoResidencia: 100
    },
    {
        id: 114,
        pais: "Malí",
        bandera: "mali.svg",
        emoji: "🇲🇱",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 25,
        estadiaMultiple: 60,
        costoMultiple: 58,
        costoResidencia: 40
    },
    {
        id: 115,
        pais: "Malta",
        bandera: "malta.svg",
        emoji: "🇲🇹",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 106
    },
    {
        id: 116,
        pais: "Marruecos",
        bandera: "marruecos.svg",
        emoji: "🇲🇦",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 15
    },
    {
        id: 117,
        pais: "Mauricio",
        bandera: "mauricio.svg",
        emoji: "🇲🇺",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        id: 118,
        pais: "Mauritania",
        bandera: "mauritania.svg",
        emoji: "🇲🇷",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 25,
        estadiaMultiple: 90,
        costoMultiple: 33,
        costoResidencia: 25
    },
    {
        id: 119,
        pais: "México",
        bandera: "mexico.svg",
        emoji: "🇲🇽",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 286
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile a nacionales de EF Micronesia con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 120,
        pais: "Micronesia",
        bandera: "micronesia.svg",
        emoji: "🇫🇲",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 25,
        estadiaMultiple: 60,
        costoMultiple: 58,
        costoResidencia: 40
    },
    {
        id: 121,
        pais: "Moldavia",
        bandera: "moldavia.svg",
        emoji: "🇲🇩",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 110
    },
    {
        id: 122,
        pais: "Mónaco",
        bandera: "monaco.svg",
        emoji: "🇲🇨",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        id: 123,
        pais: "Mongolia",
        bandera: "mongolia.svg",
        emoji: "🇲🇳",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 39
    },
    {
        id: 124,
        pais: "Montenegro",
        bandera: "montenegro.svg",
        emoji: "🇲🇪",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        id: 125,
        pais: "Mozambique",
        bandera: "mozambique.svg",
        emoji: "🇲🇿",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 128,
        estadiaMultiple: 90,
        costoMultiple: 246,
        costoResidencia: 299
    },
    {
        id: 126,
        pais: "Myanmar",
        bandera: "myanmar.svg",
        emoji: "🇲🇲",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 29,
        estadiaMultiple: 90,
        costoMultiple: 61,
        costoResidencia: 100
    },
    {
        id: 127,
        pais: "Namibia",
        bandera: "namibia.svg",
        emoji: "🇳🇦",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 71,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 64
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile de nacionales de Naurú con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 128,
        pais: "Naurú",
        bandera: "nauru.svg",
        emoji: "🇳🇷",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 0,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 40
    },
    {
        id: 129,
        pais: "Nepal",
        bandera: "nepal.svg",
        emoji: "🇳🇵",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 40,
        estadiaMultiple: 90,
        costoMultiple: 108,
        costoResidencia: 10
    },
    {
        id: 130,
        pais: "Nicaragua",
        bandera: "nicaragua.svg",
        emoji: "🇳🇮",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 267
    },
    {
        id: 131,
        pais: "Níger",
        bandera: "niger.svg",
        emoji: "🇳🇪",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 60
    },
    {
        id: 132,
        pais: "Nigeria",
        bandera: "nigeria.svg",
        emoji: "🇳🇬",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 200,
        estadiaMultiple: 60,
        costoMultiple: 208,
        costoResidencia: 200
    },
    {
        id: 133,
        pais: "Niue",
        bandera: "niue.svg",
        emoji: "🇳🇺",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        id: 134,
        pais: "Noruega",
        bandera: "noruega.svg",
        emoji: "🇳🇴",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 1239
    },
    {
        id: 135,
        pais: "Nueva Zelanda",
        bandera: "nz.svg",
        emoji: "🇳🇿",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 1478
    },
    {
        id: 136,
        pais: "Omán",
        bandera: "oman.svg",
        emoji: "🇴🇲",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 14,
        estadiaMultiple: 60,
        costoMultiple: 138,
        costoResidencia: 52
    },
    {
        id: 137,
        pais: "Países Bajos",
        bandera: "paises-bajos.svg",
        emoji: "🇳🇱",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 192
    },
    {
        id: 138,
        pais: "Pakistán",
        bandera: "pakistan.svg",
        emoji: "🇵🇰",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 122,
        estadiaMultiple: 90,
        costoMultiple: 202,
        costoResidencia: 170
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile a nacionales de República de Palaos con residencia permanente en países de la Alianza del Pacífico (Colombia-MéxicoPerú) a contar del 16 junio 2017
        id: 139,
        pais: "Palaos",
        bandera: "palaos.svg",
        emoji: "🇵🇼",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        id: 140,
        pais: "Palestina",
        bandera: "palestina.svg",
        emoji: "🇵🇸",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        id: 141,
        pais: "Panamá",
        bandera: "panama.svg",
        emoji: "🇵🇦",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 1100
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile de nacionales de Papúa Nueva Guinea con residencia permanente en países de la Alianza del Pacífico (Colombia-MéxicoPerú) a contar del 30 junio 2016
        id: 142,
        pais: "Papúa Nueva Guinea",
        bandera: "papua.svg",
        emoji: "🇵🇬",
        permiso: "si",
        estadiaSimple: 60,
        costoSimple: 0,
        estadiaMultiple: 60,
        costoMultiple: 0,
        costoResidencia: 310
    },
    {
        id: 143,
        pais: "Paraguay",
        bandera: "paraguay.svg",
        emoji: "🇵🇾",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 288
    },
    {
        id: 144,
        pais: "Perú",
        bandera: "peru.svg",
        emoji: "🇵🇪",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 80
    },
    {
        id: 145,
        pais: "Polonia",
        bandera: "polonia.svg",
        emoji: "🇵🇱",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 65
    },
    {
        id: 146,
        pais: "Portugal",
        bandera: "portugal.svg",
        emoji: "🇵🇹",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 85
    },
    {
        id: 147,
        pais: "Qatar",
        bandera: "qatar.svg",
        emoji: "🇶🇦",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 27,
        estadiaMultiple: 30,
        costoMultiple: 35,
        costoResidencia: 70
    },
    {
        id: 148,
        pais: "Reino Unido",
        bandera: "uk.svg",
        emoji: "🇬🇧",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 2620
    },
    {
        id: 149,
        pais: "República Centroafricana",
        bandera: "republica-centroafricana.svg",
        emoji: "🇨🇫",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 60
    },
    {
        id: 150,
        pais: "República Checa",
        bandera: "republica-checa.svg",
        emoji: "🇨🇿",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 120
    },
    {
        id: 151,
        pais: "República del Congo",
        bandera: "republica-congo.svg",
        emoji: "🇨🇬",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 25,
        estadiaMultiple: 60,
        costoMultiple: 50,
        costoResidencia: 40
    },
    {
        id: 152,
        pais: "República Democrática del Congo",
        bandera: "republica-democratica.svg",
        emoji: "🇨🇩",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 70,
        estadiaMultiple: 90,
        costoMultiple: 78,
        costoResidencia: 70
    },
    {
        // Nacionales de República Dominicana portadores de una Visa otorgada por EE.UU. (Todos los tipos excepto la Visa C) con a lo menos 6 meses de vigencia, o Green Card, No requieren VISTUR para ingresar a Chile a contar del 1 de abril de 2019
        id: 153,
        pais: "República Dominicana",
        bandera: "republica-dominicana.svg",
        emoji: "🇩🇴",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 10,
        estadiaMultiple: 30,
        costoMultiple: 18,
        costoResidencia: 195
    },
    {
        id: 154,
        pais: "Ruanda",
        bandera: "ruanda.svg",
        emoji: "🇷🇼",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: 90,
        costoMultiple: 68,
        costoResidencia: 40
    },
    {
        id: 155,
        pais: "Rumania",
        bandera: "rumania.svg",
        emoji: "🇷🇴",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 138
    },
    {
        id: 156,
        pais: "Rusia",
        bandera: "rusia.svg",
        emoji: "🇷🇺",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 90
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile de nacionales de Samoa con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 157,
        pais: "Samoa",
        bandera: "samoa.svg",
        emoji: "🇼🇸",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 0,
        estadiaMultiple: 30,
        costoMultiple: 0,
        costoResidencia: 250
    },
    {
        id: 158,
        pais: "San Cristóbal y Nieves",
        bandera: "san-cristobal.svg",
        emoji: "🇰🇳",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 223
    },
    {
        id: 159,
        pais: "San Marino",
        bandera: "san-marino.svg",
        emoji: "🇸🇲",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 102
    },
    {
        id: 160,
        pais: "San Vicente y las Granadinas",
        bandera: "san-vicente.svg",
        emoji: "🇻🇨",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 670
    },
    {
        id: 161,
        pais: "Santa Lucía",
        bandera: "santa-lucia.svg",
        emoji: "🇱🇨",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 280
    },
    {
        id: 162,
        pais: "Santa Sede",
        bandera: "santa-sede.svg",
        emoji: "🇻🇦",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 0
    },
    {
        id: 163,
        pais: "Santo Tomé y Príncipe",
        bandera: "santo-tome.svg",
        emoji: "🇸🇹",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 25,
        estadiaMultiple: 60,
        costoMultiple: 58,
        costoResidencia: 40
    },
    {
        id: 164,
        pais: "Senegal",
        bandera: "senegal.svg",
        emoji: "🇸🇳",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 25,
        estadiaMultiple: 60,
        costoMultiple: 58,
        costoResidencia: 40
    },
    {
        id: 165,
        pais: "Serbia",
        bandera: "serbia.svg",
        emoji: "🇷🇸",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 153
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile de nacionales de Seychelles con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 16 junio 2017
        id: 166,
        pais: "Seychelles",
        bandera: "seychelles.svg",
        emoji: "🇸🇨",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 40
    },
    {
        id: 167,
        pais: "Sierra Leona",
        bandera: "sierra-leona.svg",
        emoji: "🇸🇱",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 60
    },
    {
        id: 168,
        pais: "Singapur",
        bandera: "singapur.svg",
        emoji: "🇸🇬",
        permiso: "no",
        estadiaSimple: 30,
        costoSimple: 0,
        estadiaMultiple: 30,
        costoMultiple: 0,
        costoResidencia: 77
    },
    {
        id: 169,
        pais: "Siria",
        bandera: "siria.svg",
        emoji: "🇸🇾",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 80,
        estadiaMultiple: 90,
        costoMultiple: 153,
        costoResidencia: 56
    },
    {
        id: 170,
        pais: "Somalia",
        bandera: "somalia.svg",
        emoji: "🇸🇴",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 60
    },
    {
        id: 171,
        pais: "Sri Lanka",
        bandera: "sri-lanka.svg",
        emoji: "🇱🇰",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 30,
        estadiaMultiple: 90,
        costoMultiple: 30,
        costoResidencia: 200
    },
    {
        id: 172,
        pais: "Suazilandia",
        bandera: "suazilandia.svg",
        emoji: "🇸🇿",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 6,
        estadiaMultiple: 90,
        costoMultiple: 27,
        costoResidencia: 89
    },
    {
        id: 173,
        pais: "Sudáfrica",
        bandera: "sudafrica.svg",
        emoji: "🇿🇦",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 115
    },
    {
        id: 174,
        pais: "Sudán",
        bandera: "sudan.svg",
        emoji: "🇸🇩",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 35,
        estadiaMultiple: 90,
        costoMultiple: 78,
        costoResidencia: 35
    },
    {
        id: 175,
        pais: "Sudán del Sur",
        bandera: "sudan-sur.svg",
        emoji: "🇸🇸",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 35,
        estadiaMultiple: 90,
        costoMultiple: 78,
        costoResidencia: 35
    },
    {
        id: 176,
        pais: "Suecia",
        bandera: "suecia.svg",
        emoji: "🇸🇪",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 103
    },
    {
        id: 177,
        pais: "Suiza",
        bandera: "suiza.svg",
        emoji: "🇨🇭",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 100
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile de nacionales de Surinam con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 178,
        pais: "Surinam",
        bandera: "surinam.svg",
        emoji: "🇸🇷",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 40,
        estadiaMultiple: 90,
        costoMultiple: 60,
        costoResidencia: 210
    },
    {
        id: 179,
        pais: "Tailandia",
        bandera: "tailandia.svg",
        emoji: "🇹🇭",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 162
    },
    {
        id: 180,
        pais: "Taiwán",
        bandera: "taiwan.svg",
        emoji: "🇹🇼",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 99
    },
    {
        id: 181,
        pais: "Tanzania",
        bandera: "tanzania.svg",
        emoji: "🇹🇿",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 50,
        estadiaMultiple: 90,
        costoMultiple: 108,
        costoResidencia: 550
    },
    {
        id: 182,
        pais: "Tayikistán",
        bandera: "tayikistan.svg",
        emoji: "🇹🇯",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: 30,
        costoMultiple: 68,
        costoResidencia: 200
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile de nacionales de Timor Oriental con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 16 junio 2017
        id: 183,
        pais: "Timor Oriental",
        bandera: "timor.svg",
        emoji: "🇹🇱",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 35,
        estadiaMultiple: 60,
        costoMultiple: 43,
        costoResidencia: 50
    },
    {
        id: 184,
        pais: "Togo",
        bandera: "togo.svg",
        emoji: "🇹🇬",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 60
    },
    {
        id: 185,
        pais: "Tonga",
        bandera: "tonga.svg",
        emoji: "🇹🇴",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        id: 186,
        pais: "Trinidad y Tobago",
        bandera: "trinidad-tobago.svg",
        emoji: "🇹🇹",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 160
    },
    {
        id: 187,
        pais: "Túnez",
        bandera: "tunez.svg",
        emoji: "🇹🇳",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        id: 188,
        pais: "Turkmenistán",
        bandera: "turkmenistan.svg",
        emoji: "🇹🇲",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 5,
        estadiaMultiple: 90,
        costoMultiple: 159,
        costoResidencia: 500
    },
    {
        id: 189,
        pais: "Turquía",
        bandera: "turquia.svg",
        emoji: "🇹🇷",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 165
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile de nacionales de Tuvalu con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 190,
        pais: "Tuvalu",
        bandera: "tuvalu.svg",
        emoji: "🇹🇻",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 12
    },
    {
        id: 191,
        pais: "Ucrania",
        bandera: "ucrania.svg",
        emoji: "🇺🇦",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 85
    },
    {
        id: 192,
        pais: "Uganda",
        bandera: "uganda.svg",
        emoji: "🇺🇬",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 50,
        estadiaMultiple: 90,
        costoMultiple: 108,
        costoResidencia: 500
    },
    {
        id: 193,
        pais: "Uruguay",
        bandera: "uruguay.svg",
        emoji: "🇺🇾",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 65
    },
    {
        id: 194,
        pais: "Uzbekistán",
        bandera: "uzbekistan.svg",
        emoji: "🇺🇿",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 60,
        estadiaMultiple: 90,
        costoMultiple: 88,
        costoResidencia: 250
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile de nacionales de Vanuatu con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 195,
        pais: "Vanuatu",
        bandera: "vanuatu.svg",
        emoji: "🇻🇺",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 23,
        estadiaMultiple: 30,
        costoMultiple: 31,
        costoResidencia: 280
    },
    {
        id: 196,
        pais: "Venezuela",
        bandera: "venezuela.svg",
        emoji: "🇻🇪",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 50,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 60
    },
    {
        id: 197,
        pais: "Vietnam",
        bandera: "vietnam.svg",
        emoji: "🇻🇳",
        permiso: "no",
        estadiaSimple: 90,
        costoSimple: 0,
        estadiaMultiple: 90,
        costoMultiple: 0,
        costoResidencia: 135
    },
    {
        id: 198,
        pais: "Yemen",
        bandera: "yemen.svg",
        emoji: "🇾🇪",
        permiso: "si",
        estadiaSimple: 60,
        costoSimple: 80,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 150
    },
    {
        id: 199,
        pais: "Yibuti",
        bandera: "yibuti.svg",
        emoji: "🇩🇯",
        permiso: "si",
        estadiaSimple: 30,
        costoSimple: 50,
        estadiaMultiple: "N/A",
        costoMultiple: "N/A",
        costoResidencia: 60
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile de nacionales de Zambia con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 30 junio 2016
        id: 200,
        pais: "Zambia",
        bandera: "zambia.svg",
        emoji: "🇿🇲",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 50,
        estadiaMultiple: 90,
        costoMultiple: 88,
        costoResidencia: 205
    },
    {
        // Exento del requisito VISTUR para ingresar a Chile de nacionales de Zimbawe con residencia permanente en países de la Alianza del Pacífico (Colombia-México-Perú) a contar del 16 junio 2017
        id: 201,
        pais: "Zimbabue",
        bandera: "zimbabue.svg",
        emoji: "🇿🇼",
        permiso: "si",
        estadiaSimple: 90,
        costoSimple: 16,
        estadiaMultiple: 90,
        costoMultiple: 32,
        costoResidencia: 100
    }
]

/* Array con ID's de países acogidos al Convenio Alianza del Pacífico - Cap:
19 (Bielorrusia), 25 (Botswana), 27 (Brunei), 29 (Burkina Faso), 33 (Camboya), 
43 (Costa de Marfil), 46 (Cuba), 48 (Dominica), 64 (Gabón), 67 (Ghana), 
86 (Islas Marshall), 87 (Islas Salomón), 96 (Kiribati), 99 (Laos), 110 (Madagascar), 
112 (Malawi), 113 (Maldivas), 120 (Micronesia), 128 (Naurú), 139 (Palaos), 
142 (Papúa Nueva Guinea), 157 (Samoa), 166 (Seychelles), 178 (Surinam), 
183 (Timor Oriental), 190 (Tuvalu), 195 (Vanuatu), 200 (Zambia), 201 (Zimbabue): */

const paisesCap = [19, 25, 27, 29, 33, 43, 46, 48, 64, 67, 86, 87, 96, 99, 110, 112, 113, 120, 128, 139, 142, 157, 166, 178, 183, 190, 195, 200, 201]
